version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - minio
    volumes:
      - .:/backend
    env_file:
      - .env
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gonogo-backend.rule=Host(`api.emplica.fr`)"
      - "traefik.http.services.gonogo-backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.gonogo-backend.entrypoints=websecure"
      - "traefik.http.routers.gonogo-backend.tls=true"
      - "traefik.http.routers.gonogo-backend.tls.certresolver=myresolver"
      - "traefik.http.routers.gonogo-backend-http.entrypoints=web"
      - "traefik.http.routers.gonogo-backend-http.middlewares=https-redirect"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gonogo-frontend.rule=Host(`emplica.fr`)"
      - "traefik.http.services.gonogo-frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.gonogo-frontend.entrypoints=websecure"
      - "traefik.http.routers.gonogo-frontend.tls=true"
      - "traefik.http.routers.gonogo-frontend.tls.certresolver=myresolver"
      - "traefik.http.routers.gonogo-frontend-http.entrypoints=web"
      - "traefik.http.routers.gonogo-frontend-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"


  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioaccesskey
      MINIO_ROOT_PASSWORD: miniosecretkey
    volumes:
      - minio_data:/data/minio
    command: 'minio server /data/minio --address ":9000" --console-address ":9001"'
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gonogo-minio.rule=Host(`minio.emplica.fr`)"
      - "traefik.http.services.gonogo-minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.gonogo-minio.entrypoints=websecure"
      - "traefik.http.routers.gonogo-minio.tls=true"
      - "traefik.http.routers.gonogo-minio.tls.certresolver=myresolver"
      - "traefik.http.routers.gonogo-minio-http.entrypoints=web"
      - "traefik.http.routers.gonogo-minio-http.middlewares=https-redirect"


networks:
  traefik_network:
    external: true

volumes:
  minio_data:
  postgres_data:

