version: '3.7'

services:
  backend:
    image: gonogo-backend
    networks:
      - traefik_network
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gonogo-backend.rule=Host(`api.emplica.fr`)"
      - "traefik.http.services.gonogo-backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.gonogo-backend.entrypoints=websecure"
      - "traefik.http.routers.gonogo-backend.tls=true"
      - "traefik.http.routers.gonogo-backend.tls.certresolver=myresolver"

  frontend:
    image: gonogo-frontend
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gonogo-frontend.rule=Host(`emplica.fr`)"
      - "traefik.http.services.gonogo-frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.gonogo-frontend.entrypoints=websecure"
      - "traefik.http.routers.gonogo-frontend.tls=true"
      - "traefik.http.routers.gonogo-frontend.tls.certresolver=myresolver"

  minio:
    image: minio/minio:latest
    networks:
      - traefik_network
    command: server /data --console-address ":9001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gonogo-minio.rule=Host(`minio.emplica.fr`)"
      - "traefik.http.services.gonogo-minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.gonogo-minio.entrypoints=websecure"
      - "traefik.http.routers.gonogo-minio.tls=true"
      - "traefik.http.routers.gonogo-minio.tls.certresolver=myresolver"

networks:
  traefik_network:
    external: true

volumes:
  minio_data:
  postgres_data:
